Repository marmelo/tech-companies-in-portugal, pull requests merged in 2022-03, with the labels that each got.

#259 add: kitch
  README.md
Labels: ➕ new company

#261 update: dengun websites
  README.md
Labels: 🐛 bug

#264 fix: platforme careers link
  README.md
Labels: 🐛 bug

#265 fix: jumo careers link
  README.md
Labels: 🐛 bug

#266 fix: alter & add career page
  README.md
Labels: 🐛 bug, ✨ enhancement

#269 Remove cloudmobility.io
  README.md
Labels: 🐛 bug
